spring.application.name=person-api
spring.datasource.url=jdbc:h2:mem:persondb
spring.datasource.username=leo
s´pring.datasource.password=senha123

# spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


#configs de logs para o terminal 
spring.output.ansi.enabled=ALWAYS 

# padrao de logs limpo e colorido 
logging.pattern.console=%clr(%d{HH:mm:ss}){cyan} | %clr(%-5level){highlight} | %clr(${spring.application.name}){magenta} | %clr(%logger{20}){yellow} | %msg%n

# reduz logs do Spring
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR
