spring.application.name=med-api
spring.datasource.url=jdbc:postgresql://localhost:5432/med_api
spring.datasource.username=postgres
spring.datasource.password=123

# servem para mostrar as consultas SQL no console, o que é útil para depuração e desenvolvimento. O spring.jpa.show-sql=true habilita a exibição das consultas SQL geradas pelo Hibernate, enquanto o spring.jpa.properties.hibernate.format_sql=true formata as consultas SQL para torná-las mais legíveis.
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
# spring.data.web.sort.sort-parameter=ordem # serve para personalizar o nome do parâmetro de ordenação usado nas requisições. Por exemplo, se você definir spring.data.web.sort.sort-parameter=ordem, em vez de usar ?sort=nome, você usaria ?ordem=nome para ordenar os resultados pela propriedade "nome".